### ISSUE TITLE
P@200 in Sketchy Extended vs that in paper

### ISSUE THREAD

**Issue by finalyXG** [leftthomas/ClipPrompt#1]
Hello! I just wanted to start by saying that you've done an amazing job! I did notice, however, that while the mAP@200 achieved in your implementation (71.92) is very close to the value reported in the paper (72.38), there seems to be a significant difference in the P@200 metric between your code (68.05) and the paper's reported value (0.725). I was wondering if you had any insights regarding this discrepancy?

**Comment by leftthomas** [comment]
@finalyXG I recommend you to ask the author for their implementation of the results which reported in their paper.
