### ISSUE TITLE
 line 373, in init self._handle = _dlopen(self._name, mode) OSError: [WinError 127] The specified program could not be found

### ISSUE THREAD

**Issue by x-28** [leftthomas/ClipPrompt#2]
Hello, I apologize for any previous lack of courtesy in my response. Regarding your question, here's a polite translation:

"Hello, I followed the instructions to set up the environment properly, but I encountered the following error when running the program: 'File "D:\Anaconda3\envs\lixue\lib\ctypes_init_.py", line 373, in init self._handle = _dlopen(self._name, mode) OSError: [WinError 127] The specified program could not be found.' Have you ever encountered this issue?"

**Comment by leftthomas** [comment]
@x-28 you should use Linux system, not Windows

**Comment by x-28** [comment]
> @x-28 you should use Linux system, not Windows

thank you

**Comment by x-28** [comment]
Thank you very much for providing the code. After reproducing the results, I noticed that during training on the Sketchy and Tuberlin datasets for 60 epochs, the training loss consistently decreased. However, the validation accuracy peaked in the first and sixth epochs and then started to decline. Additionally, the best achieved mAP@200 and P@200 on the Sketchy dataset were lower than the reported 0.4 in the paper. I wanted to inquire if you have encountered such a situation before and if there might be any issues with me. Your guidance would be greatly appreciated.

**Comment by x-28** [comment]
Thank you for providing the code. After reproducing the results, I observed a peculiar pattern in the training process on the Sketchy and Tuberlin datasets. Over the course of 60 epochs, the training loss consistently decreased. However, the validation accuracy showed the best performance in the first and sixth epochs before gradually declining. This trend was particularly noticeable in the Sketchy dataset, where the accuracy even dropped below the initial level. I wanted to inquire whether you have encountered a similar situation during training or if there might be any issues with my reproduction. Your guidance would be greatly appreciated.

**Comment by leftthomas** [comment]
@x-28 yes, I have encountered this situation, I think this may be related to learning rate and weight decay, you could try to use other learning rate and weight decay to see the results.

**Comment by leftthomas** [comment]
@x-28 yes, I have encountered this situation, I think this may be related to learning rate and weight decay, you could try to use other learning rate and weight decay to see the results.
